### ISSUE TITLE
Tiny feedback

### ISSUE THREAD

**Issue by luciusmagn** [reasonablecow/rust-learning#2]
https://github.com/reasonablecow/rust-learning/blob/3e12b607116957924fb3a47bea3cf1e97fc66d23/hw02/src/main.rs#L7

You can shrink these into one import statement:

```rust
use std::io::{self, Read};
```

**Comment by reasonablecow** [comment]
It took me a while to get used to these nested imports. Especially comming from python, where one import on one line is considered a good practice.
The change of my habits is first noticable here https://github.com/reasonablecow/rust-learning/blob/hw05/cli-ser/src/lib.rs#L7-L15
