### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by luciusmagn** [reasonablecow/rust-learning#4]
https://github.com/reasonablecow/rust-learning/blob/f00db04cfd480da798ba44c630cc0e862d85fa4c/text-tool/src/lib.rs#L105-L123

That's one sexy iterator chain :D

**Comment by reasonablecow** [comment]
Is it ok? 😅
I find it readable, especially when formated by hand such as this
```rs
    write!(f, "{}",
        self.rows.iter().map(|row| {
            format!("|{}|\n",
                row.iter()
                    .zip(widths.iter())
                    .map(|(field, width)| format!(" {:width$} ", field, width = width))
                    .collect::<Vec<_>>()
                    .join("|")
            )}
        ).collect::<Vec<_>>()
        .concat()
    )
```
but, of course, it could have been split into a few let statements...

**Comment by luciusmagn** [comment]
Yeah, it is perfectly fine :D
